# These settings are to provide information about your theme
# and should follow the format
# default:
#   name: Default theme
# An optional configuration for theme colors can be defined, which will add
# a button to the appearance colors section of the admin dashboard, allowing
# the user to easily set the custom colors. Only colors which are included
# will be overwritten from the defaults.
#   theme_custom_colors:
#     collection_banner_text_color: '#000000'
#     default_button_background_color: '#FFFFFF'
#     default_button_border_color: '#5B5B5B'
#
default_home:
  banner_image: true
  featured_researcher: true
  home_page_text: false
  marketing_text: true
  name: Default home
  notes: This theme is the default Hyku view
wvu:
  banner_image: true
  featured_researcher: false
  home_page_text: true
  marketing_text: true
  name: WVU Theme
  notes: This theme is recommended for West Virginia University
  theme_custom_colors:
    # collection_banner_text_color: '#000000'
    # default_button_background_color: '#FFFFFF'
    # default_button_border_color: '#5B5B5B'
    # default_button_text_color: '#CE8C00'
    # facet_panel_background_color: '#FFFFFF'
    # facet_panel_text_color: '#985F03'
    # footer_link_color: '#985F03'
    # header_and_footer_text_color: '#000000'
    # link_color: '#985F03'
    # link_hover_color: '#FFBD42'
    # primary_button_background_color: '#FFFFFF'
    # primary_button_border_color: '#CE8C00'
    # primary_button_hover_color: '#215480'
    # primary_button_text_color: '#985F03'
cultural_repository:
  banner_image: true
  featured_researcher: false
  home_page_text: true
  marketing_text: true
  name: Cultural Repository
  notes: This theme is recommended for cultural repositories
institutional_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Institutional Repository
  notes: This theme is recommended for institutional repositories
neutral_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Neutral Repository
  notes: This theme is neutral and is recommended for all types of repositories
