# These settings are to provide information about your theme
# and should follow the format
# default:
#   name: Default theme
# An optional configuration for theme colors can be defined, which will add
# a button to the appearance colors section of the admin dashboard, allowing
# the user to easily set the custom colors. Only colors which are included
# will be overwritten from the defaults.
#   theme_custom_colors:
#     collection_banner_text_color: '#000000'
#     default_button_background_color: '#FFFFFF'
#     default_button_border_color: '#5B5B5B'
#
default_home:
  banner_image: true
  featured_researcher: true
  home_page_text: false
  marketing_text: true
  name: Default home
  notes: This theme is the default Hyku view
wvu_home:
  banner_image: true
  featured_researcher: false
  home_page_text: true
  marketing_text: true
  name: WVU Home Page
  notes: This theme is recommended for West Virginia University
  theme_custom_colors:
    primary_button_background_color: '#EEAA00'
    primary_button_border_color: '#002855'
    primary_button_hover_color: '#002855'
    primary_button_text_color: '#F7F7F7'
    header_and_footer_background_color: '#002855'
    header_and_footer_text_color: '#F7F7F7'
    navbar_background_color: '#EEAA00'
    navbar_link_background_color: '#002855'
    navbar_link_background_hover_color: '#F7F7F7'
    navbar_link_text_color: '#F7F7F7'
    navbar_link_text_hover_color: '#F7F7F7'
    link_color: '#0062A3'
    link_hover_color: '#002855'
    default_button_background_color: '#F7F7F7'
    default_button_border_color: '#BEB7B3'
    default_button_text_color: '#1C2B39'
    collection_banner_text_color: '#1C2B39'
    facet_panel_background_color: '#F7F7F7'
    facet_panel_text_color: '#1C2B39'
    active_tabs_background_color: '#F7DD63'
    footer_link_color: '#B3A169'
    footer_link_hover_color: '#EEAA00'
cultural_repository:
  banner_image: true
  featured_researcher: false
  home_page_text: true
  marketing_text: true
  name: Cultural Repository
  notes: This theme is recommended for cultural repositories
institutional_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Institutional Repository
  notes: This theme is recommended for institutional repositories
neutral_repository:
  banner_image: true
  featured_researcher: true
  home_page_text: true
  marketing_text: true
  name: Neutral Repository
  notes: This theme is neutral and is recommended for all types of repositories
